server:
  port: 9090

---
spring:
  profiles:
    active: prod

---
spring:
  profiles: dev
  data:
    mongodb:
      host: local
      port: 27017
      database: ItemDB

---
spring:
  profiles: uat
  data:
    mongodb:
      host: mongo
      port: 27017
      database: ItemDB

---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongo
      port: 27017
      database: ItemDB
