spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/dev}

#---
#spring:
#  profiles:
#    active: dev
#---
##data:
##  mongodb:
##    uri=${MONGO_URL:mongodb://localhost:27017/dev}
#spring:
#  profiles: dev
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: ItemDB
#
#---
#spring:
#  profiles: uat
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: ItemDB
#
#---
#spring:
#  profiles: prod
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: ItemDB
